<?php
if (!defined('PHPWG_ROOT_PATH')) die('Hacking attempt!');

// 权限检查
check_status(ACCESS_ADMINISTRATOR);

global $template, $page, $conf;
load_language('plugin.lang', EASY_CONFIG_PATH);

$EC_ACTION = get_admin_plugin_menu_link(dirname(__FILE__).'/admin.php');

// 下载配置文件
if (isset($_POST['download_config'])) {
    if (file_exists(CUSTOM_CONFIG_PATH)) {
        // 清除缓冲区，防止之前的输出污染文件内容
        if (ob_get_level()) ob_end_clean();
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="config_ec.inc.php"');
        header('Content-Length: ' . filesize(CUSTOM_CONFIG_PATH));
        readfile(CUSTOM_CONFIG_PATH);
        exit;
    } else {
        $page['errors'][] = l10n('ec_file_not_found');
    }
}

// 删除配置
if (isset($_POST['delete_all_config'])) {
    if (file_exists(CUSTOM_CONFIG_PATH)) {
        if (unlink(CUSTOM_CONFIG_PATH)) {
            $page['infos'][] = l10n('ec_delete_success');
        } else {
            $page['errors'][] = l10n('ec_delete_error');
        }
    }
}

// 保存处理
if (isset($_POST['save_config'])) {
    $content_to_save = "<?php\n";
    $content_to_save .= "// Generated by EasyConfig Plugin\n";
    $content_to_save .= "// Last update: " . date('Y-m-d H:i:s') . "\n\n";

    $posted_conf = isset($_POST['conf']) ? $_POST['conf'] : array();
    $posted_types = isset($_POST['conf_type']) ? $_POST['conf_type'] : array();

    foreach ($posted_conf as $key => $value) {
        $clean_value = stripslashes(trim($value));
        
        // 值被删除，不写入
        if ($clean_value === '') continue;

        // 勾选了恢复默认，不写入
        if (isset($_POST['use_default'][$key]) && $_POST['use_default'][$key] == 1) continue;

        $type = isset($posted_types[$key]) ? $posted_types[$key] : 'string';
        $val_str = '';

        // 特殊值处理
        if (strcasecmp($clean_value, 'NULL') === 0) {
            $val_str = 'null';
        } 
        elseif ($clean_value === '""' || $clean_value === "''") {
            $val_str = "''";
        } 
        else {
            switch ($type) {
                case 'bool':
                    $val_str = ($clean_value == '1' || strtolower($clean_value) == 'true') ? 'true' : 'false';
                    break;
                    
                case 'number':
                    if (preg_match('/^[\d\s\+\-\*\/\.\(\)]+$/', $clean_value)) {
                        $val_str = preg_replace('/\s+/', '', $clean_value);
                    } else {
                        $val_str = '0';
                    }
                    break;

                case 'php':
                    $val_str = $clean_value;
                    break;

                case 'string':
                default:
                    $val_str = var_export($clean_value, true);
                    break;
            }
        }

        $content_to_save .= "\$conf['" . $key . "'] = " . $val_str . ";\n";
    }

    $content_to_save .= "?>";

    // 备份并写入
    if (file_exists(CUSTOM_CONFIG_PATH)) {
        copy(CUSTOM_CONFIG_PATH, CUSTOM_CONFIG_PATH . '.bak');
    }

    if (file_put_contents(CUSTOM_CONFIG_PATH, $content_to_save)) {
        if (function_exists('opcache_invalidate')) opcache_invalidate(CUSTOM_CONFIG_PATH, true);
        $page['infos'][] = l10n('ec_saved_success');
    } else {
        $page['errors'][] = l10n('ec_saved_error');
    }
}

// 读取已保存的自定义配置
$saved_conf = array();

if (file_exists(CUSTOM_CONFIG_PATH)) {
    $content = file_get_contents(CUSTOM_CONFIG_PATH);
    $tokens = token_get_all($content);
    $count = count($tokens);

    for ($i = 0; $i < $count; $i++) {
        $t = $tokens[$i];

        // 寻找配置变量
        if (is_array($t) && $t[0] === T_VARIABLE && $t[1] === '$conf') {
            
            $next_idx = $i + 1;
            
            $find_next = function($start, $tokens, $limit) {
                for ($j = $start; $j < $limit; $j++) {
                    if (is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) continue;
                    return $j;
                }
                return false;
            };

            // 找[
            $idx_bracket_open = $find_next($next_idx, $tokens, $count);
            if ($idx_bracket_open === false || $tokens[$idx_bracket_open] !== '[') continue;

            // 找key
            $idx_key = $find_next($idx_bracket_open + 1, $tokens, $count);
            if ($idx_key === false) continue;
            
            $key_token = $tokens[$idx_key];
            $key_name = null;

            if (is_array($key_token)) {
                if ($key_token[0] === T_CONSTANT_ENCAPSED_STRING) {
                    $key_name = substr($key_token[1], 1, -1);
                } elseif ($key_token[0] === T_LNUMBER) {
                    $key_name = $key_token[1];
                }
            }
            if ($key_name === null) continue;

            // 早]
            $idx_bracket_close = $find_next($idx_key + 1, $tokens, $count);
            if ($idx_bracket_close === false || $tokens[$idx_bracket_close] !== ']') continue;

            // 找=
            $idx_equals = $find_next($idx_bracket_close + 1, $tokens, $count);
            if ($idx_equals === false || $tokens[$idx_equals] !== '=') continue;

            // 提取值
            $value_buffer = '';
            $curr = $idx_equals + 1;
            
            while ($curr < $count) {
                $tok = $tokens[$curr];
                if ($tok === ';') break; // 语句结束
                
                if (is_array($tok)) {
                    $value_buffer .= $tok[1];
                } else {
                    $value_buffer .= $tok;
                }
                $curr++;
            }

            // 保存提取到的原始代码值
            $saved_conf[$key_name] = trim($value_buffer);
            $i = $curr;
        }
    }
}

// 解析config_default.inc.php
$lines = file(DEFAULT_CONFIG_DIR);
$parsed_items = array();
$comment_buffer = "";
$is_in_multiline_comment = false;
$conf_multiline_buffer = '';
$is_in_conf_multiline = false;
foreach ($lines as $line) {
    $trim_line = trim($line);

    // 处理空行
    if (empty($trim_line)) {
        if (!empty($comment_buffer)) $comment_buffer .= "<br>";
        continue;
    }

    // 开始多行注释
    if (strpos($trim_line, '/**') === 0) {
        $is_in_multiline_comment = true;
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }
    
    // 结束多行注释
    if (strpos($trim_line, '*/') !== false && $is_in_multiline_comment) {
        $is_in_multiline_comment = false;
        $comment_buffer .= format_comment_line($trim_line) . "<br>";
        continue;
    }

    // 多行注释中
    if ($is_in_multiline_comment) {
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }

    // 单行注释
    if (strpos($trim_line, '//') === 0) {
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }

    // 处理配置行
    $target_line  = $is_in_conf_multiline ? $conf_multiline_buffer : $trim_line;
    if (preg_match('/^\$conf\[[\'"]([^\'"]+)[\'"]\]\s*=\s*(.+);/', $target_line, $matches)) {
        $parsed_items[] = build_config_item(
            $matches[1],
            $matches[2],
            $saved_conf,
            $lang,
            $comment_buffer
        );

        $comment_buffer = "";
        $conf_multiline_buffer = '';
        $is_in_conf_multiline = false;
        continue;
    }

    if (strpos($line, '$conf[') === 0) {
        $conf_multiline_buffer = $trim_line;
        $is_in_conf_multiline  = true;
    } elseif ($is_in_conf_multiline) {
        $conf_multiline_buffer .= $trim_line;
    }
}

/**
 * 构建配置项
 */
function build_config_item($key, $raw_default_value, $saved_conf, $lang, $comment_buffer) {
    $is_customized = array_key_exists($key, $saved_conf);
    
    // 类型判断
    $type = 'string';
    $raw_lower = strtolower($raw_default_value);
    if ($raw_lower === 'true' || $raw_lower === 'false') {
        $type = 'bool';
    } elseif (preg_match('/^[\d\s\+\-\*\/\.\(\)]+$/', $raw_default_value)) {
        $type = 'number';
    } elseif (
        strpos($raw_default_value, 'array(') === 0 || 
        strpos($raw_default_value, '[') === 0 || 
        strpos($raw_default_value, 'array_merge') !== false
    ) {
        $type = 'php';
    } else {
        $type = 'string';
    }

    $current_val_display = '';
    
    if ($is_customized) {
        $raw_val = $saved_conf[$key];
        
        if (strcasecmp($raw_val, 'null') === 0) {
             $current_val_display = 'NULL';
        } elseif ($type === 'bool') {
            $current_val_display = (strtolower($raw_val) === 'true' || $raw_val === '1') ? 'true' : 'false';
        } elseif ($type === 'string') {
            $first = substr($raw_val, 0, 1);
            $last = substr($raw_val, -1);
            
            if (($first === "'" && $last === "'") || ($first === '"' && $last === '"')) {
                $inner = substr($raw_val, 1, -1);
                $current_val_display = stripslashes($inner);
            } else {
                $current_val_display = $raw_val;
            }
        } else {
            $current_val_display = $raw_val;
        }
        if ($raw_val === "''" || $raw_val === '""') {
            $current_val_display = '""';
        }
    }

    $default_display = $raw_default_value;
    if ($type == 'string') $default_display = trim($raw_default_value, "'\"");
    // 创建翻译键名
    $lang_key = 'conf_desc_' . $key;
    $final_description = isset($lang[$lang_key]) ? $lang[$lang_key] : $comment_buffer;

    return [
        'key' => $key,
        'type' => $type,
        'default_raw' => $default_display,
        'description' => $final_description,
        'current_value' => $current_val_display,
        'is_customized' => $is_customized
    ];
}

/**
 * 去除注释符号
 */
function format_comment_line($line) {
    $line = str_replace(array('/**', '*/', '//'), '', $line);
    $line = trim($line, "* \t\n\r\0\x0B");
    return $line . " ";
}

$template->assign(array(
    'parsed_items' => $parsed_items,
    'EC_ACTION' => $EC_ACTION
));

$template->set_filename('easy_config', dirname(__FILE__) . '/admin.tpl');
$template->assign_var_from_handle('ADMIN_CONTENT', 'easy_config');
?>