<?php
if (!defined('PHPWG_ROOT_PATH')) die('Hacking attempt!');

// 权限检查
check_status(ACCESS_ADMINISTRATOR);

global $template, $page, $conf;
load_language('plugin.lang', EASY_CONFIG_PATH);

$default_config_path = DEFAULT_CONFIG_DIR;
$custom_config_path = CUSTOM_CONFIG_PATH;
$EC_ACTION = get_admin_plugin_menu_link(dirname(__FILE__).'/admin.php');

// 下载配置文件
if (isset($_POST['download_config'])) {
    if (file_exists($custom_config_path)) {
        // 清除缓冲区，防止之前的输出污染文件内容
        if (ob_get_level()) ob_end_clean();

        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="config_ec.inc.php"');
        header('Content-Length: ' . filesize($custom_config_path));
        
        readfile($custom_config_path);
        exit;
    } else {
        $page['errors'][] = $lang['ec_file_not_found'];
    }
}

// 删除配置
if (isset($_POST['delete_all_config'])) {
    if (file_exists($custom_config_path)) {
        if (unlink($custom_config_path)) {
            $page['infos'][] =$lang['ec_delete_success'];
        } else {
            $page['errors'][] = $lang['ec_delete_error'];
        }
    }
}

// 保存处理
if (isset($_POST['save_config'])) {
    $content_to_save = "<?php\n";
    $content_to_save .= "// Generated by EasyConfig Plugin\n";
    $content_to_save .= "// Last update: " . date('Y-m-d H:i:s') . "\n\n";

    foreach ($_POST['conf'] as $key => $value) {
        $clean_value = trim($value);
        
        // 值被删除，不写入
        if ($clean_value === '') continue;

        // 勾选了恢复默认，不写入
        if (isset($_POST['use_default'][$key]) && $_POST['use_default'][$key] == 1) continue;

        // 简单的类型推断
        if (strtolower($clean_value) === 'true') {
            $val_str = 'true';
        } elseif (strtolower($clean_value) === 'false') {
            $val_str = 'false';
        } elseif (is_numeric($clean_value)) {
            $val_str = $clean_value;
        } elseif (strpos($clean_value, 'array(') === 0 || strpos($clean_value, '[') === 0) {
            // 数组原样保留
            $val_str = stripslashes($clean_value);
        } else {
            // 其他写为字符串，添加引号
            $val_str = "'" . str_replace("'", "\'", $clean_value) . "'";
        }

        $content_to_save .= "\$conf['" . $key . "'] = " . $val_str . ";\n";
    }

    $content_to_save .= "?>";

    if (file_put_contents($custom_config_path, $content_to_save)) {
        $page['infos'][] = l10n('ec_saved_success');
    } else {
        $page['errors'][] = l10n('ec_saved_error');
    }
}

// 读取已保存的自定义配置
$saved_conf = array();
if (file_exists($custom_config_path)) {
    // 防止载入缓存
    if (function_exists('opcache_invalidate')) {
        opcache_invalidate($custom_config_path, true);
    }
    $saved_conf = (function($path) {
        $conf = array();
        include($path);
        return $conf;
    })($custom_config_path);
}

// 解析config_default.inc.php
$lines = file($default_config_path);
$parsed_items = array();
$comment_buffer = "";
$is_in_multiline_comment = false;
$conf_multiline_buffer = '';
$is_in_conf_multiline = false;
foreach ($lines as $line) {
    $trim_line = trim($line);

    // 处理空行
    if (empty($trim_line)) {
        if (!empty($comment_buffer)) $comment_buffer .= "<br>";
        continue;
    }

    // 开始多行注释
    if (strpos($trim_line, '/**') === 0) {
        $is_in_multiline_comment = true;
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }
    
    // 结束多行注释
    if (strpos($trim_line, '*/') !== false && $is_in_multiline_comment) {
        $is_in_multiline_comment = false;
        $comment_buffer .= format_comment_line($trim_line) . "<br>";
        continue;
    }

    // 多行注释中
    if ($is_in_multiline_comment) {
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }

    // 单行注释
    if (strpos($trim_line, '//') === 0) {
        $comment_buffer .= format_comment_line($trim_line);
        continue;
    }

    // 处理配置行
    $target_line  = $is_in_conf_multiline ? $conf_multiline_buffer : $trim_line;
    if (preg_match('/^\$conf\[[\'"]([^\'"]+)[\'"]\]\s*=\s*(.+);/', $target_line, $matches)) {
        $parsed_items[] = build_config_item(
            $matches[1],
            $matches[2],
            $saved_conf,
            $lang,
            $comment_buffer
        );

        $comment_buffer = "";
        $conf_multiline_buffer = '';
        $is_in_conf_multiline = false;
        continue;
    }

    if (strpos($line, '$conf[') === 0) {
        $conf_multiline_buffer = $trim_line;
        $is_in_conf_multiline  = true;
    } elseif ($is_in_conf_multiline) {
        $conf_multiline_buffer .= $trim_line;
    }
}

/**
 * 构建配置项
 */
function build_config_item($key, $raw_default_value, $saved_conf, $lang, $comment_buffer) {
    // 优先显示已保存的自定义值
    $current_value = isset($saved_conf[$key]) ? var_export_string($saved_conf[$key]) : '';
    $is_customized = isset($saved_conf[$key]);

    // 创建翻译键名
    $lang_key = 'conf_desc_' . $key;
    $final_description = isset($lang[$lang_key]) ? $lang[$lang_key] : $comment_buffer;

    return [
        'key' => $key,
        'default_raw' => $raw_default_value,
        'description' => $final_description,
        'current_value' => $current_value,
        'is_customized' => $is_customized
    ];
}

/**
 * 去除注释符号
 */
function format_comment_line($line) {
    $line = str_replace(array('/**', '*/', '//'), '', $line);
    $line = trim($line, "* \t\n\r\0\x0B");
    return $line . " ";
}

/**
 * 将PHP值转为字符串显示
 */
function var_export_string($val) {
    if (is_array($val)) {
        $export = var_export($val, true);
        $export = preg_replace(['/\s+/', '/\d+ => /'], [' ', ''], $export);
        $export = str_replace('array ( ', 'array(', $export);
        $export = str_replace(', )', ')', $export);
        return $export;
    } elseif (is_bool($val)) {
        return $val ? 'true' : 'false';
    } else {
        return $val;
    }
}

$template->assign(array(
    'parsed_items' => $parsed_items,
    'EC_ACTION' => get_admin_plugin_menu_link(dirname(__FILE__).'/admin.php')
));

$template->set_filename('easy_config', dirname(__FILE__) . '/admin.tpl');
$template->assign_var_from_handle('ADMIN_CONTENT', 'easy_config');
?>